### ISSUE TITLE
11.18 Исправить ошибку "controlled input is changed to be uncontrolled"

### ISSUE THREAD

**Issue by kirillchistov** [kirillchistov/mesto-react#34]
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at label
    at fieldset
    at form
    at div
    at div
    at PopupWithForm (http://localhost:3000/static/js/bundle.js:1730:5)
    at EditProfilePopup (http://localhost:3000/static/js/bundle.js:1027:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:318:110)

Решение здесь: https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro  и обсуждение [здесь](https://practicum-students.slack.com/archives/C035GNX79GW/p1662733870453999)

**Comment by kirillchistov** [comment]
Поправил
